scons: move -lm to end of link line
Some versions of GCC/binutils pay special attention to the position of the -l arguments:

    gcc -o cpuid -pthread -lm cache.o clock.o cpuid.o feature.o handlers.o main.o sanity.o threads.o util.o version.o getopt/getopt_long.o
    clock.o: In function `wallclock_ns':
    clock.c:(.text+0xd): undefined reference to `clock_gettime'
    clock.o: In function `calibrate_cpu_clock':
    clock.c:(.text+0x11c): undefined reference to `sqrt'
    clock.c:(.text+0x141): undefined reference to `fmax'
    clock.c:(.text+0x158): undefined reference to `fmin'
    collect2: ld returned 1 exit status
    scons: *** [cpuid] Error 1
    scons: building terminated because of errors.

Signed-off-by: Steven Noonan <steven@uplinklabs.net>